// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZOZCiV-rq7GUYyOFrZo-sivYBIY-j3pM',
    appId: '1:383254817735:web:1c2cda9311099d0aad87e2',
    messagingSenderId: '383254817735',
    projectId: 'eazytechno-35351',
    authDomain: 'eazytechno-35351.firebaseapp.com',
    storageBucket: 'eazytechno-35351.appspot.com',
    measurementId: 'G-3FNF3XGH2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVG3OAGz5DNZot7RbZrt8rW_g-zMqswLY',
    appId: '1:383254817735:android:72dbba101e2c346fad87e2',
    messagingSenderId: '383254817735',
    projectId: 'eazytechno-35351',
    storageBucket: 'eazytechno-35351.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNv4Zp6zE5KJ3wzZTd00OyzwmZ31hNZqM',
    appId: '1:383254817735:ios:9ea9b5f51c68fd81ad87e2',
    messagingSenderId: '383254817735',
    projectId: 'eazytechno-35351',
    storageBucket: 'eazytechno-35351.appspot.com',
    iosClientId: '383254817735-hvls3i669ohqnuhkt7thhqahnq308in7.apps.googleusercontent.com',
    iosBundleId: 'com.eazytechno.eazyTechnoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNv4Zp6zE5KJ3wzZTd00OyzwmZ31hNZqM',
    appId: '1:383254817735:ios:73c8fc14302f4996ad87e2',
    messagingSenderId: '383254817735',
    projectId: 'eazytechno-35351',
    storageBucket: 'eazytechno-35351.appspot.com',
    iosClientId: '383254817735-nr9oilgm0hso7uoddi3i3mdoft75hcb3.apps.googleusercontent.com',
    iosBundleId: 'com.eazytechno.eazyTechnoApplication.RunnerTests',
  );
}
